const PROFILE_VALIDATION = {
  MIN_NAME_LENGTH: 2,
  MAX_NAME_LENGTH: 40,
  MAX_BIO_LENGTH: 200,
  MAX_DISTRICT_LENGTH: 60,
  MAX_LANGUAGE_LENGTH: 30,
  MAX_INTERESTS: 10,
  SUPPORTED_LANGUAGES: ['English', 'Sinhala', 'Tamil'],
  MAX_INTEREST_LABEL_LENGTH: 30,
};

module.exports = PROFILE_VALIDATION;
